server:
  port: 8081

spring:
  application:
    name: USER-MANAGMENT-SERVICE

# SPRING CLOUD CONFIGURATION
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    discovery:
      enabled: true
