server:
  port: 8081

spring:
  application:
    name: USER-MANAGEMENT-SERVICE

  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

user:
  password: "{cipher}AgBtyX0zoZ5+9LKIJdrgdVGlWlIY9mGyW9sL/YxGbAqLOC+xXj09/nYRmG1OiC50ZNupWKJPC08zlZLLWepLzADfvfldwTEJyheHZbNI8WF2arOI+qC5s7+DFf1Q4XiFqdTnVRjj5fvw3+LdGCVjkrf1NnIhGyGnQ+chQ2Sa6pymtl5M+hAlvRW//kPUtEAm1pOfIyLjKGwBVU7ksc5RgHdgCiwJ34JIXnI7WvqdwpiQT4pPvmCZSZNzNB0IyAMUoUoJv+B5LVxqRCmF2DkeJ5qRurqIMygeeWD0huwGvpwp4HH/SahS5KDke6wiVCCZ4mzrZ//duf5C4fjwdxpgns8lQyES2g7sgsTLPiQ3SY76wktCe0UKY3JS5MAwBOEAWFd/tQCloFIvZ4b8kAGs4qwfigEPbJP4uj9gpfrYS5E/0dQk/z315jHxIgCDDY8EbqfpXZUM75Rd3SrFZ6xpH9IVftFyUxZ/Msf3CEK9ETJu8njuXwwXKJtn0QTARebPyHqf6XH99hjH1sldeVflNTqmpGXcydN0OmxWBXz/1QCY0WLvdwt325WsKsvldS3YMwLORCFaeloHHfTfPq/PFzwUmrntmDm0vKL1AR5tJwEPCEsWCia9An0Pj+IllmcMDXyNZMpeosn4a+60ecmnEMVQ9oLaFjHEhBd2xYSBgLtaSxNqumj+ftxVF9W4bTok0czn3jsT093InKAoINLKsXvb"
