server:
  port: 8081

spring:
  application:
    name: USER-MANAGEMENT-SERVICE

  cloud:
    discovery:
      enabled: true

  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloudinary:
  cloud-name: "{cipher}AgCEDGwODCV5Nod9kau86pfd1ECkCunQEcGpms5wm8Tn9HTIn/Q+HwY860biTgTGOBxgWrWFK/c3qWkPKJoF2R42geaiie+Cz4n78VczZPsrEy77bkdXEvrZ0lDd6EGKh8s5r5NsyeaumUaU3ScrJpIXpdZTYc3jzTkEVHVCNnBL/H4Qr+S3tKIkZKUJ7vzsMecPsKiO+E3aQMR8zJO1QH4LQsPHPXue2TlNIP8ll9Q6a5LgvDPWI99Bk8BN+/KtCSqlBjk7W077Y6nJAJctSHBqCWXhw/9EHHN5n5dHj2Bo8tXjdkLGv1TWX+455H+Hb54g+xIOXhkhDAr7QA0JfvHgGLoLfnG/8OwHN9kynHd4wIb85jC0Dr734Xzr+rG1tZmPYA4/0DdThE/eW04xTsjDX9EckBfL1VEUn8wCpNZwxU5HmxLpRsENULoGK0amnO/xv+nNqRpJM9daqJ1/Ug65Sv+rrRL3A+8qhCIcYXKsToioQlJ7cliHYQ5TksJBEZz8IpBDSFFQxAS2YWcgsSooanOxOxJS3U/imZEjCHHH5QxDKJq88crya0syXQC+528BNN8wf8niBzSGqkhgCAe8ZKoVCJIKCtGzZKWSCjx5txMvj8LwNtdtrBMadcsCZtgwX2PGr5rIZl1Fwm8lUTx5v/GBooHyqaBio50mmfYKBPdYF9MEOsyDxH3D/aXiXpB/Ig7FK0q+6JxUK/yG2TKk"
  api-key: "{cipher}AgCSEiCX7UNfeVRQ7pUrbmHLbA0w/AkPf2etiIXQgwR2/F5MfsQ2srbmTSmee+8lkID1ec4EM3R/7zKFgWVxJID/0uXNGN1l4OC2e4hUVBg+PIOwDAnIIC8eAp0fLAESISfSd/X9LWJy868WnO2MB6pZXRw3vr9iQw7u4qJ1DXJXG+xXwnaRO6pLXfAu5/MESWdQlJO5Oir3I0594Xs6nj6QPbUs6ieo4xkS1aRMmm9IXnpOO5GQu7weksAlqTd/4GNklHzt1s4oW/GxLVX4kKMKUs7JUiUpFdANWk1JPPVDiOzKbDIwmWIQzoAc43O+YlZZUeV8pDiss0u7VVH9IBZOfPGi9hShR0wfqmuiNhTXJc+QvmA9bSTgWxVqPXFkiAlMz2Vhu0YVugQiQXB2Ag5LG05zdyEPV65LtXaroJWHieb8Olm2eDFXgSkBw8omTEGCROmlRCBi/DdsLLhazjKOAFbgfHOp9z64KFqPAJNsGd7XsPigjNYqJREb3dsbbDiGA1hLHmCcHZjW5qq1anKIh7TEPBcyAHLGr+YbWstiMk4E/0+3qvuzLnYi6BNMQi9LVnlcCrQBIwl/2ZAzsXvtTUc47HWKqF+QFpUfD6Loatbb4J+xKa1LpOAsvmFu14SoQ9OjIy54AUmejf+8Ff3vkQ1gfb5mJXUBN3gSsY3eH1PFkdm5310spy6thyLcILhGPJi5wtg1byupfrY7/ymZ"
  api-secret: "{cipher}AgBCD2IGZvltNP8tHkLKHgBkqXPiLs6no+AnpitwmfqWTYv9tjDcMxstMdud2WJp3TTXHZb6vTxsVlPgSwEAEAI8KpKdm+rQddOsbNx8izIxeYUKIrFhshP7z+EPoIfCdVeUIeyFxokxCOXI/Ybs89o3xc1LGOb2htgX9N5YdOId7mACxdgZJvis0ynE1k9Lpr7xcYcmHXj+tCHU4AgcVQKeQg05YGfvXOmJiJwD6mIDwYbiPU2Y13MO67WzsZvZk+vRx/3IRruFYA/PYIALf+f3kBoonXaCczNKeEIljvxYamnsKJXjrfjguDcXlYcI5kqkvKtipziQ55+OpWYTAH0kbm2DkHAxa5luJQbfZFTA2RouooBZg9vSU2vEItQjhv2yMJXJBfDniqhFLF3BRNJcsweXqVGRbO/M9uEige/6qCIZQRC8YGG4+Qnaqy7mLcip7782P+WlLLEU/sqMVg2Bd7woY6qNrQZk29ZHAKCOrYPqRYc86bD2Ni4WnukLZ7yVZb38vpksz7JBxsVa7qBDIsuxykoyk0UGPDPQaKMYA8Nxy3XfD3UPnrbalhU/RddEpPeVoKwgxSIxV16/Mv82hVuOLNGx9vfFFZUB6mcJ/6JYd9MaFSw/eGpGFOWEA8vUDwvVJky8xAxm1Sf/0bLTswF4MPxu1PWfB0LTo5s0dSqeaZGNRan0iqCADdFG1PKD6iO0LFTLncQ1hwD1VzdAI9rxczwiIc0siAQPDWdm5w=="
