server:
  port: 8081

spring:
  application:
    name: USER-MANAGMENT-SERVICE

  cloud:
    discovery:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
